//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Xml.Schema;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class patentInfo
    {

        private string tanField;

        private languageType languageField;

        /// <remarks/>
        public string tan
        {
            get
            {
                return this.tanField;
            }
            set
            {
                this.tanField = value;
            }
        }

        /// <remarks/>
        public languageType language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    public enum languageType
    {

        /// <remarks/>
        de,

        /// <remarks/>
        en,

        /// <remarks/>
        fr,

        /// <remarks/>
        ja,

        /// <remarks/>
        zh,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nameType
    {

        private nameType[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private string[] textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bold", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("ital", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("scriptfont", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("smallcap", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("sub", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("subsub", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("subsup", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("sup", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("supsub", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("supsup", typeof(nameType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public nameType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        bold,

        /// <remarks/>
        ital,

        /// <remarks/>
        scriptfont,

        /// <remarks/>
        smallcap,

        /// <remarks/>
        sub,

        /// <remarks/>
        subsub,

        /// <remarks/>
        subsup,

        /// <remarks/>
        sup,

        /// <remarks/>
        supsub,

        /// <remarks/>
        supsup,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class patentLocation
    {

        private string pageNumberField;

        private string pageLabelField;

        private string exampleLabelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string pageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }

        /// <remarks/>
        public string pageLabel
        {
            get
            {
                return this.pageLabelField;
            }
            set
            {
                this.pageLabelField = value;
            }
        }

        /// <remarks/>
        public string exampleLabel
        {
            get
            {
                return this.exampleLabelField;
            }
            set
            {
                this.exampleLabelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class name : nameType
    {

        private languageType langField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public languageType lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class names
    {

        private name[] nameField;

        private nameType iUPACNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public name[] name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public nameType IUPACName
        {
            get
            {
                return this.iUPACNameField;
            }
            set
            {
                this.iUPACNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("structureData", Namespace = "", IsNullable = false)]
    public partial class structureDataType
    {

        private structureDataTypeType typeField;

        private structureDataTypeEncoding encodingField;

        private byte[] valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public structureDataTypeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public structureDataTypeEncoding encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum structureDataTypeType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MDL Molfile V2000")]
        MDLMolfileV2000,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum structureDataTypeEncoding
    {

        /// <remarks/>
        Base64,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class propheticSubstance
    {

        private patentLocation patentLocationField;

        private names namesField;

        private structureDataType structureDataField;

        /// <remarks/>
        public patentLocation patentLocation
        {
            get
            {
                return this.patentLocationField;
            }
            set
            {
                this.patentLocationField = value;
            }
        }

        /// <remarks/>
        public names names
        {
            get
            {
                return this.namesField;
            }
            set
            {
                this.namesField = value;
            }
        }

        /// <remarks/>
        public structureDataType structureData
        {
            get
            {
                return this.structureDataField;
            }
            set
            {
                this.structureDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class propheticSubstances
    {

        private propheticSubstance[] propheticSubstanceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("propheticSubstance")]
        public propheticSubstance[] propheticSubstance
        {
            get
            {
                return this.propheticSubstanceField;
            }
            set
            {
                this.propheticSubstanceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class patent
    {

        [XmlAttribute("noNamespaceSchemaLocation", Namespace = XmlSchema.InstanceNamespace)]
        public string attr = "PatentEnhancedPrioritySubstanceIndexing-2.3.xsd";

        private patentInfo patentInfoField;

        private propheticSubstances propheticSubstancesField;

        /// <remarks/>
        public patentInfo patentInfo
        {
            get
            {
                return this.patentInfoField;
            }
            set
            {
                this.patentInfoField = value;
            }
        }

        /// <remarks/>
        public propheticSubstances propheticSubstances
        {
            get
            {
                return this.propheticSubstancesField;
            }
            set
            {
                this.propheticSubstancesField = value;
            }
        }
    }

